services:
    combyna.type.loader:
        class: Combyna\Component\Type\Config\Loader\DelegatingTypeLoader
        autowire: true

    combyna.type.loader.any:
        class: Combyna\Component\Type\Config\Loader\AnyTypeLoader
        autowire: true
        tags:
            - {name: combyna.type_loader}

    combyna.type.loader.exotic:
        class: Combyna\Component\Type\Config\Loader\ExoticTypeLoader
        autowire: true
        tags:
            - {name: combyna.type_loader}

    combyna.type.loader.multiple:
        class: Combyna\Component\Type\Config\Loader\MultipleTypeLoader
        autowire: true
        tags:
            - {name: combyna.type_loader}

    combyna.type.loader.static_list:
        class: Combyna\Component\Type\Config\Loader\StaticListTypeLoader
        autowire: true
        tags:
            - {name: combyna.type_loader}

    combyna.type.loader.static_structure:
        class: Combyna\Component\Type\Config\Loader\StaticStructureTypeLoader
        autowire: true
        tags:
            - {name: combyna.type_loader}

    combyna.type.loader.static:
        class: Combyna\Component\Type\Config\Loader\StaticTypeLoader
        autowire: true
        tags:
            - {name: combyna.type_loader}

    combyna.type.loader.valued:
        class: Combyna\Component\Type\Config\Loader\ValuedTypeLoader
        autowire: true
        tags:
            - {name: combyna.type_loader}
