services:
    combyna.config.loader.argument_parser:
        class: Combyna\Component\Config\Loader\ArgumentParser
        autowire: true

    combyna.config.loader.array_walker:
        class: Combyna\Component\Config\Loader\ArrayWalker
        autowire: true

    combyna.config.loader.config_parser:
        class: Combyna\Component\Config\Loader\ConfigParser
        autowire: true
        autowiring_types: Combyna\Component\Config\Loader\ConfigParserInterface
